name: cloudipsp_mobile
description: Cloudipsp SDK for Mobile(Android, iOS)
version: 0.0.4
author: Maxim Kozenko
homepage: https://github.com/erfanjazebnikoo/flutter_cloudipsp

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.10
  http: ^0.13.3
  email_validator: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16


flutter:
  plugin:
    platforms:
      android:
        package: com.cloudipsp.mobile
        pluginClass: CloudipspMobilePlugin
      ios:
        pluginClass: CloudipspMobilePlugin
